### ISSUE TITLE
Volunteer form update

### ISSUE THREAD

**Issue by sidPhoenix17** [sidPhoenix17/covidsos#28]
.

**Comment by sidPhoenix17** [comment]
Make sure that if a url is www.covidsos.org/?source=source_name then a field called source still needs to be sent with value 'source_name'

**Comment by sidPhoenix17** [comment]
Also, improve the UI. Looks compressed and congested in mobile right now.

**Comment by sidPhoenix17** [comment]
Remove flat number & email ID. Send '' for these fields to the backend

**Comment by sidPhoenix17** [comment]
- Need to interchange the flow of the two screens for volunteer signup.

- Make sure that if a url is www.covidsos.org/?source=source_name then a field called source still needs to be sent with value 'source_name'

- Also, improve the UI. Looks compressed and congested in mobile right now.

- Remove flat number & email ID. Send '' for these fields to the backend

**Comment by chiragb1994** [comment]
- Need to interchange the flow of the two screens for volunteer signup.
  - Done
- Make sure that if a url is www.covidsos.org/?source=source_name then a field called source still needs to be sent with value 'source_name'
  - Checked. Working
- Remove flat number & email ID. Send '' for these fields to the backend
  - Done
