### ISSUE TITLE
FAQs page

### ISSUE THREAD

**Issue by sidPhoenix17** [sidPhoenix17/covidsos#30]
- Create an FAQ page as per "After Login Screen3" which takes user to page with embedding of 

https://docs.google.com/document/d/162D6YrrjibmEIl-gn8Bue1ADRyoe-0gsB7TllnNYTcE/edit

- Integrate into "Accept" Screen flow
"Have further queries?" button on bottom of page should go to "FAQ page" 

- Integrate into "Volunteer" login flow
See the screen "After login Screen2" ( https://stg.covidsos.org/task-status-update/d54c377e3a0d49c4be7a3da59b040b9d ) on https://www.figma.com/file/vfxEQsL0C43sVExiUP8CVw/Covid-SOS?node-id=0%3A1
(Currently only update status button is live)

**Comment by chiragb1994** [comment]
All done and merged in ui revamp
