### ISSUE TITLE
Social media icons on bottom of every page

### ISSUE THREAD

**Issue by sidPhoenix17** [sidPhoenix17/covidsos#31]
Instagram https://www.instagram.com/covid_sos_org/
Facebook https://www.facebook.com/covidsos.org/
Twitter https://twitter.com/covid_sos_org

**Comment by skathuria29** [comment]
Rather than just adding media icons on bottom of every page. Can we create a generic footer with other information like copyright,  contact us, social media and FAQs links on the bottom?
