### ISSUE TITLE
Change home page of [ADMIN]

### ISSUE THREAD

**Issue by sidPhoenix17** [sidPhoenix17/covidsos#34]
[Unverified], [Unassigned], [Assigned], [Completed]

Click and reaches respective page. Each page has filter of location, financial help and urgency

**Comment by sidPhoenix17** [comment]
1. Add new Request - NGO request form - @stgstg27 is making this
2. Add new Volunteer - Regular form (source should be organization name of user)
3. Unverified Requests - Current API without Verify button
4. Pending requests - Same 
5. In-progress requests - Same
6. Completed requests - Same

**Comment by sidPhoenix17** [comment]
These are all cards on homescreen. 
Let's remove the map and put it in sidebar.

**Comment by chiragb1994** [comment]
done in 34-home-page
