### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by sidPhoenix17** [sidPhoenix17/covidsos#39]
Rather than just adding media icons on bottom of every page. Can we create a generic footer with other information like copyright,  contact us, social media and FAQs links on the bottom?

_Originally posted by @skathuria29 in https://github.com/sidPhoenix17/covidsos/issues/31#issuecomment-620125413_

**Comment by chiragb1994** [comment]
There is already a footer component: https://github.com/sidPhoenix17/covidsos/blob/master/src/components/Footers/AdminFooter.js

Just add the content to this

**Comment by sidPhoenix17** [comment]
@stgstg27
