### ISSUE TITLE
Home page v2 minor changes

### ISSUE THREAD

**Issue by sidPhoenix17** [sidPhoenix17/covidsos#63]
1. Carousel needed for cards on top instead of 2 multiple boxes
2. Desktop view needs to be done for the carousel
3. Change wordings of cards to "GET HELP" and "VOLUNTEER" along with icons as per the figma screen - https://www.figma.com/file/vfxEQsL0C43sVExiUP8CVw/Covid-SOS?node-id=0%3A1
Should the color be changed too ? Not necessarily, can be checked once.
4. The pending requests header click should take user to the pending-requests page

**Comment by chiragb1994** [comment]
All done
