### ISSUE TITLE
Volunteer form

### ISSUE THREAD

**Issue by sidPhoenix17** [sidPhoenix17/covidsos#80]
Issues being faced on registering - 
1. Remove the previous button - poor positioning 
![Screenshot_20200512-152514_Chrome](https://user-images.githubusercontent.com/16644933/81671550-b73c9f80-9466-11ea-8393-9a22674f9526.jpg)

2. Check if Google address drop-down has any issues

![IMG-20200512-WA0033](https://user-images.githubusercontent.com/16644933/81671463-a55afc80-9466-11ea-8a06-7989f1cedafb.jpg)

![IMG-20200512-WA0032](https://user-images.githubusercontent.com/16644933/81671452-a2f8a280-9466-11ea-8ffe-ea4cb3055624.jpg)

**Comment by chiragb1994** [comment]
1 is fixed
2 doesn't seem to work. will try again

**Comment by chiragb1994** [comment]
2 also fixed
