### ISSUE TITLE
updates to admin cards [ADMIN]

### ISSUE THREAD

**Issue by sidPhoenix17** [sidPhoenix17/covidsos#83]
1. "new", "pending", "in-progress" and "completed" cards in admin panel need upgrade to new UI.
2. New card to have "managed by" and "assign to me" button like old cards
3. In case of pop-up opening in public "pending-requests" on www.covidsos.org/pending-requests , the button should say "See Details".
4. In case someone clicks on "See Details" should have "share" and "talk to us" directly visible on pop-up, instead of after clicking on "accept" again 
4. In case of pop-up opening in admin "pending-requests", add a "assign a volunteer" button

**Comment by chiragb1994** [comment]
1 - done
2 - done
3 - done

**Comment by chiragb1994** [comment]
5 - done

**Comment by chiragb1994** [comment]
#74 to be done with 4
