### ISSUE TITLE
Pending requests differentiator

### ISSUE THREAD

**Issue by sidPhoenix17** [sidPhoenix17/covidsos#87]
Three categories of requests:
a. Pending requests near you (<1km)
b. Pending requests slightly further away (>1km and <10kms) 
c. Far requests (>10kms)

Case 1: No requests within 10 Kms. 

"There are no pending requests nearby😃😃😃. Please search another locality/city where you have good friends share with them on <WhatsApp_icon>"
Show c

Case B: No request within 1 km but there is request within 10kms

"There are pending requests slightly away from your location 🙁🙁🙁. Please share with someone who can help <WhatsApp_icon>"
Show b
breaker
Show c

Case C: There is request within 1km

Show a
Show b
Show c

**Comment by chiragb1994** [comment]
done and merged in master
